### ISSUE TITLE
Running tugboat within a docker image fails

### ISSUE THREAD

**Issue by jvliwanag** [softprops/tugboat#12]
I'm trying to figure this out.

I'm running an application which uses tugboat within a docker container and mounts `/var/run/docker.sock` from the host. Running regular `docker` commands form the command line within the docker container works. However, running commands within tugboat fails with the following:

```
java.net.ConnectException: http://localhost/_ping
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103) ~[com.ning.async-http-client-1.8.10.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[io.netty.netty-3.9.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145) ~[io.netty.netty-3.9.6.Final.jar:na]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1138) ~[com.ning.async-http-client-1.8.10.jar:na]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:935) ~[com.ning.async-http-client-1.8.10.jar:na]
        at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499) ~[com.ning.async-http-client-1.8.10.jar:na]
 
...

Caused by: java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:123) ~[na:1.8.0_40-internal]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_40-internal]
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108) ~[io.netty.netty-3.9.6.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70) ~[io.netty.netty-3.9.6.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) ~[io.netty.netty-3.9.6.Final.jar:na]
```

Any idea?

**Comment by softprops** [comment]
I probably won't have a change to take a look until next week, but off the top my head. Here's the code that tries to resolve an address for [docker](https://github.com/softprops/tugboat/blob/master/src/main/scala/Docker.scala#L119-L124). is the `DOCKER_HOST` env var set maybe. I may be doing something wrong with that. It should fallback on the `unix:///var/run/docker.sock` address.

**Comment by softprops** [comment]
Also, if that's the source of the problem you can try and set it explicitly as a [constructor](https://github.com/softprops/tugboat/blob/master/src/main/scala/Docker.scala#L237) arg

**Comment by jvliwanag** [comment]
Thanks for the hint. The `DOCKER_HOST` env variable is not set. It does fall back to `unix:///var/run/docker.sock`. I can confirm this since I print out `docker.hostStr`.

When using the unix socket, I see that there's code that creates an http proxy around it. I'm guessing the problem lies somewhere there.

**Comment by jvliwanag** [comment]
Looks like this seems to be the case when running outside of sbt. See #13
